# Generated by Django 4.1.6 on 2023-10-09 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_testomonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testomonial',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='testomonials'),
        ),
    ]
