# Generated by Django 4.1.6 on 2023-06-07 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nepaliclass',
            name='students',
            field=models.ManyToManyField(blank=True, to='users.nepalistudent'),
        ),
        migrations.AddField(
            model_name='nepaliclass',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
        ),
        migrations.AddField(
            model_name='danceclass',
            name='students',
            field=models.ManyToManyField(blank=True, to='users.dancestudent'),
        ),
        migrations.AddField(
            model_name='danceclass',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
        ),
    ]
