# Generated by Django 4.1.6 on 2023-06-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_danceclass_teacher_alter_nepaliclass_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danceclass',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='nepaliclass',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
