# Generated by Django 4.1.6 on 2023-06-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_alter_danceclass_name_alter_nepaliclass_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.FileField(upload_to='assignments/')),
            ],
        ),
    ]
