# Generated by Django 4.1.6 on 2023-06-12 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_alter_assignment_assignment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
