# Generated by Django 4.1.6 on 2023-06-12 08:44

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('classes', '0008_assignment_assignmentsubmission_assignmentfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='student',
            field=models.ForeignKey(limit_choices_to={'nepali_class_pk': django.db.models.expressions.OuterRef('assignment__nepali_class')}, on_delete=django.db.models.deletion.CASCADE, to='users.nepalistudent'),
        ),
    ]
