# Generated by Django 4.1.6 on 2023-06-12 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('classes', '0014_alter_assignmentsubmission_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignmentsubmission',
            options={'verbose_name_plural': 'Assignment Submissions'},
        ),
        migrations.AlterUniqueTogether(
            name='assignmentsubmission',
            unique_together={('assignment', 'student')},
        ),
    ]
