# Generated by Django 4.1.6 on 2023-10-13 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_dancestudent_other_classes_and_more'),
        ('classes', '0015_alter_assignmentsubmission_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nepaliclass',
            name='students',
            field=models.ManyToManyField(to='users.nepalistudent'),
        ),
    ]
