# Generated by Django 4.1.6 on 2023-10-27 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0016_alter_nepaliclass_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=250)),
                ('dance_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.danceclass')),
            ],
        ),
    ]
