# Generated by Django 4.1.6 on 2023-11-01 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0018_nepaliclass_day_nepaliclass_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nepaliclass',
            name='day',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=100, verbose_name='Class Day'),
        ),
    ]
