# Generated by Django 4.1.6 on 2023-11-02 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0020_danceclass_class_type_danceclass_day_danceclass_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 11, 2, 16, 40, 43, 145214, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 2, 16, 40, 51, 659925, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='assignmentfile',
            name='a_file',
            field=models.FileField(upload_to='assignments/', verbose_name='Homework File'),
        ),
    ]
