# Generated by Django 4.1.6 on 2023-11-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0022_alter_assignment_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
