# Generated by Django 4.1.6 on 2023-11-08 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0024_remove_assignmentsubmission_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentfile',
            name='assignment_submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_files', to='classes.assignmentsubmission'),
        ),
    ]
