# Generated by Django 4.1.6 on 2024-04-01 16:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0026_assignment_deleted_at_assignment_updated_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assignment",
            old_name="file",
            new_name="file_f",
        ),
    ]
