# Generated by Django 4.1.6 on 2024-01-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_chatroom_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatroom",
            name="name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Room Name"
            ),
        ),
    ]
