# Generated by Django 4.1.6 on 2024-02-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_alter_chatroom_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
