# Generated by Django 4.1.6 on 2024-02-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0005_chatmessage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="chat_images"),
        ),
    ]
