# Generated by Django 4.1.6 on 2024-08-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_group_person_membership_group_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(help_text='hllo world', max_length=100),
        ),
    ]
