# Generated by Django 4.1.6 on 2023-03-25 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_dancestudent_class_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nepalistudent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
