# Generated by Django 4.1.6 on 2023-10-11 03:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_nepalistudent_class_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nepalistudent',
            name='class_time',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Sunday Morning', 'Sunday Morning')], max_length=20), blank=True, null=True, size=None),
        ),
    ]
