# Generated by Django 4.1.6 on 2023-03-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_nepalistudent_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dancestudent',
            name='special_request',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nepalistudent',
            name='special_request',
            field=models.TextField(blank=True, null=True),
        ),
    ]
