# Generated by Django 4.1.6 on 2023-04-20 03:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_dancestudent_special_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managementstaff',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='created_at',
        ),
        migrations.AddField(
            model_name='token',
            name='expiration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dancestudent',
            name='session_type',
            field=models.CharField(choices=[('Group Class 1 seesion per week', 'Group Class 1 session per week'), ('Group Class 2 seesion per week', 'Group Class 2 session per week'), ('One-One class 1 session per week', 'One-One class 1 session per week'), ('One-One class 2 session per week', 'One-One class 2 session per week')], max_length=32),
        ),
        migrations.AlterField(
            model_name='nepalistudent',
            name='session_type',
            field=models.CharField(choices=[('Group Class 1 seesion per week', 'Group Class 1 session per week'), ('Group Class 2 seesion per week', 'Group Class 2 session per week'), ('One-One class 1 session per week', 'One-One class 1 session per week'), ('One-One class 2 session per week', 'One-One class 2 session per week')], max_length=32),
        ),
    ]
