# Generated by Django 4.1.6 on 2023-10-11 03:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_nepalistudent_class_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nepalistudent',
            name='class_time',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, choices=[('Sunday Morning', 'Sunday Morning'), ('Sunday Evening', 'Sunday Evening'), ('Monday Morning', 'Monday Morning'), ('Monday Evening', 'Monday Evening'), ('Tuesday Morning', 'Tuesday Morning'), ('Tuesday Evening', 'Tuesday Evening'), ('Wednesday Morning', 'Wednesday Morning'), ('Wednesday Evening', 'Wednesday Evening'), ('Thursday Morning', 'Thursday Morning'), ('Thursday Evening', 'Thursday Evening'), ('Friday Morning', 'Friday Morning'), ('Friday Evening', 'Friday Evening'), ('Saturday Morning', 'Saturday Morning'), ('Saturday Evening', 'Saturday Evening')], default=list, null=True, size=None),
        ),
    ]
