# Generated by Django 4.1.6 on 2023-04-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_managementstaff_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(db_index=True, max_length=128, unique=True, verbose_name='Key'),
        ),
    ]
