# Generated by Django 4.1.6 on 2023-04-28 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_management_staff_managementstaff_is_management_staff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dancestudent',
            old_name='is_Dance_student',
            new_name='is_dance_student',
        ),
    ]
