# Generated by Django 4.1.6 on 2023-10-11 16:30

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_nepalistudent_class_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nepalistudent',
            name='class_time',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Sunday Morning', 'Sunday Morning'), ('Sunday Evening', 'Sunday Evening'), ('Monday Morning', 'Monday Morning'), ('Monday Evening', 'Monday Evening'), ('Tuesday Morning', 'Tuesday Morning'), ('Tuesday Evening', 'Tuesday Evening'), ('Wednesday Morning', 'Wednesday Morning'), ('Wednesday Evening', 'Wednesday Evening'), ('Thursday Morning', 'Thursday Morning'), ('Thursday Evening', 'Thursday Evening'), ('Friday Morning', 'Friday Morning'), ('Friday Evening', 'Friday Evening'), ('Saturday Morning', 'Saturday Morning'), ('Saturday Evening', 'Saturday Evening')], max_length=100, null=True),
        ),
    ]
