# Generated by Django 4.1.6 on 2023-11-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_dancestudent_other_classes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Nepali Student', 'Nepali Student'), ('Dance Student', 'Dance Student'), ('Nepali Teacher', 'Nepali Teacher'), ('Dance Teacher', 'Dance Teacher')], max_length=20, null=True),
        ),
    ]
