# Generated by Django 4.1.6 on 2023-11-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dancestudent',
            name='is_dance_student',
        ),
        migrations.RemoveField(
            model_name='nepalistudent',
            name='is_nepali_student',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='is_teacher',
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
