# Generated by Django 4.1.6 on 2023-11-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_dancestudent_other_classes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dancestudent',
            name='dance_skills',
            field=models.CharField(choices=[('0', '0 (None)'), ('1', '1 (Low)'), ('2', '2 (Medium)'), ('3', '3 (Good)'), ('4', '4 (Very Good)'), ('5', '5 (Well)')], max_length=1),
        ),
        migrations.AlterField(
            model_name='nepalistudent',
            name='listening',
            field=models.CharField(choices=[('0', '0 (None)'), ('1', '1 (Low)'), ('2', '2 (Medium)'), ('3', '3 (Good)'), ('4', '4 (Very Good)'), ('5', '5 (Well)')], max_length=1),
        ),
        migrations.AlterField(
            model_name='nepalistudent',
            name='reading',
            field=models.CharField(choices=[('0', '0 (None)'), ('1', '1 (Low)'), ('2', '2 (Medium)'), ('3', '3 (Good)'), ('4', '4 (Very Good)'), ('5', '5 (Well)')], max_length=1),
        ),
        migrations.AlterField(
            model_name='nepalistudent',
            name='speaking',
            field=models.CharField(choices=[('0', '0 (None)'), ('1', '1 (Low)'), ('2', '2 (Medium)'), ('3', '3 (Good)'), ('4', '4 (Very Good)'), ('5', '5 (Well)')], max_length=1),
        ),
        migrations.AlterField(
            model_name='nepalistudent',
            name='writing',
            field=models.CharField(choices=[('0', '0 (None)'), ('1', '1 (Low)'), ('2', '2 (Medium)'), ('3', '3 (Good)'), ('4', '4 (Very Good)'), ('5', '5 (Well)')], max_length=1),
        ),
    ]
