# Generated by Django 4.1.6 on 2023-11-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_dancestudent_dance_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Nepali Student', 'Nepali Student'), ('Dance Student', 'Dance Student'), ('Nepali Teacher', 'Nepali Teacher'), ('Dance Teacher', 'Dance Teacher'), ('Admin', 'Admin')], max_length=20, null=True),
        ),
    ]
