# Generated by Django 4.1.6 on 2023-12-03 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_alter_user_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dancestudent",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dance_student",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("Nepali Student", "Nepali Student"),
                    ("Dance Student", "Dance Student"),
                    ("Nepali Teacher", "Nepali Teacher"),
                    ("Dance Teacher", "Dance Teacher"),
                    ("Admin", "Admin"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
