# Generated by Django 4.1.6 on 2023-12-03 09:17

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0017_alter_dancestudent_user_alter_user_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("Nepali Student", "Nepali Student"),
                    ("Dance Student", "Dance Student"),
                    ("Nepali Teacher", "Nepali Teacher"),
                    ("Dance Teacher", "Dance Teacher"),
                    ("Admin", "Admin"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
