# Generated by Django 4.1.6 on 2023-12-03 09:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0018_alter_user_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("Nepali Student", "Nepali Student"),
                        ("Dance Student", "Dance Student"),
                        ("Nepali Teacher", "Nepali Teacher"),
                        ("Dance Teacher", "Dance Teacher"),
                        ("Admin", "Admin"),
                    ],
                    max_length=255,
                    null=True,
                ),
                default=["Nepali Student"],
                size=None,
            ),
            preserve_default=False,
        ),
    ]
