# Generated by Django 4.1.6 on 2024-02-20 16:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0021_alter_user_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("Nepali Student", "Nepali Student"),
                        ("Dance Student", "Dance Student"),
                        ("Nepali Teacher", "Nepali Teacher"),
                        ("Dance Teacher", "Dance Teacher"),
                        ("Admin", "Admin"),
                        ("Management", "Management"),
                    ],
                    max_length=255,
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
