# Generated by Django 4.1.6 on 2024-07-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_opt'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('adminVideo', models.FileField(upload_to='adminVideos/')),
                ('clientVideo', models.FileField(upload_to='clientVideos/')),
            ],
        ),
    ]
