# Generated by Django 4.1.6 on 2024-07-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_videoupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoupload',
            name='adminVideo',
            field=models.FileField(blank=True, null=True, upload_to='adminVideos/'),
        ),
        migrations.AlterField(
            model_name='videoupload',
            name='clientVideo',
            field=models.FileField(blank=True, null=True, upload_to='clientVideos/'),
        ),
    ]
